### ISSUE TITLE
TypeError: this.sql.lastIndexOf is not a function in index.js

### ISSUE THREAD

**Issue by danilodeveloper** [jfgodoy/knex-postgis#28]
Hello all!
When I try to add an alias to raw sql like this:
```javascript
fieldsToReturn.push(knex.raw(geo.distance('geo_location',geo.makePointGeography(location.lon,location.lat))).as('distance'));

knex('core.tabletest')
                .select(fieldsToReturn)
            .whereRaw(geo.dwithin('geo_location',geo.makePointGeography(location.lon,location.lat),1000))
                .orderByRaw(geo.distance('geo_location', geo.makePointGeography(location.lon,location.lat)));
```
I'm getting the error below (in index.js line 115):
```
TypeError: this.sql.lastIndexOf is not a function
    at Raw.as (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/knex-postgis/lib/index.js:115:34)
    at /Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/business/pick_up_point/pick_up_point_business.js:57:123
    at Generator.next (<anonymous>)
    at Function.findPickUpPointByNearLocation (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/business/pick_up_point/pick_up_point_business.js:64:11)
    at findPickUpPointByNearLocation (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/routes/api/v1/pick_up_point_router.js:34:52)
    at /Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/utils/router/router_util.js:3:9
    at Layer.handle [as handle_request] (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/express/lib/router/layer.js:95:5)
    at /Users/danilodeveloper/Projetos/recebepramim/recebepramim-core-api/node_modules/express/lib/router/index.js:281:22
```

```json
    "knex": "0.15.2",
    "knex-postgis": "0.7.0",
    "pg": "7.4.3"
```

Does anyone know how to fix this?
Tks!!

**Comment by danilodeveloper** [comment]
Hi @jfgodoy ,
Thank you for your help! I'm gonna do what you suggested.
